### ISSUE TITLE
Functions should reject `"."` as input

### ISSUE THREAD

**Issue by chrisdone** [chrisdone/path#13]

**Comment by chrisdone** [comment]
@mrkkrp Bumped on Hackage as `0.5.4`.

**Comment by mrkkrp** [comment]
Thanks!

**Comment by mrkkrp** [comment]
Oh, wait. This is not quite right. `...` is a valid file name.

**Comment by mrkkrp** [comment]
@chrisdone, I fear you were too fast to put it on Hackage, this will reject valid file names that consist of more then 2 dots.

**Comment by chrisdone** [comment]
@mrkkrp Hmm, `...` doesn't seem like a sensible filename, but you're right, it's valid. I'll change the check. Don't worry, I don't expect this to ruin anyone's day.

**Comment by chrisdone** [comment]
Okay, I pushed the check that only test for `"."` and `".."`. Test suite updated to ensure `...` parses.

**Comment by mrkkrp** [comment]
Nice. Thank you!
