### ISSUE TITLE
Is Dir vs File really useful?

### ISSUE THREAD

**Issue by hasufell** [chrisdone/path#16]
I'm in the process of removing all String/FilePath stuff from my [WIP file manager](https://github.com/hasufell/hsfm).

I found this library to be the most interesting for that so far. However, when dealing with the filesystem on a lower level, a lot of operations work the same on regular files and directories. In the end, they are both "files" anyway and the information about the correct file type is encoded in a more sophisticated way that is tied to the IO code. In that sense... if you need correct information about the file type, you will do that differently anyway and then you have two layers to deal with, one of which is redundant. Or in other words: sometimes I deal with directories in the sense of "files" and sometimes as directories (when I read the contents). But functions like `dirname`, `filename` and `(</>)` don't allow me to use a generic `t` instead of `Dir`/`File`. So this would involve a lot of back-and-forth conversion and would make the File/Dir distinction somewhat ambiguous, which is exactly what it is anyway.

So I wonder if it really makes sense to encode the Dir/File information in this library.

edit: or to make it more concrete... how would you write:
```hs
getContents :: Path b Dir -> [Path Rel ???]
```

**Comment by mrkkrp** [comment]
I'm using this library/approach for several months now and the only thing I can say that it certainly has saved me from some hours spent debugging. I really don't see how `Dir` vs `File` is not useful. When you use `removeDirectory`, you need a directory, `removeFile` needs a file. I've written a companion package, `path-io`:

https://hackage.haskell.org/package/path-io-1.0.1/docs/Path-IO.html

It provides well-typed wrappers around `directory` and `temporary`, so you don't need to use `toFilePath` so often (and introduce bugs this way). In combination, `path` and `path-io` are just wonderful. You can see how scanning of directories is implemented in `path-io`.

**Comment by chrisdone** [comment]
A file manager is a special case, I think. The stack project makes heavy
use of the distinction.

**Comment by hasufell** [comment]
> I really don't see how Dir vs File is not useful.

The point is... you can encode that information on the "constructor level" instead, which still allows you to not care whether something is a directory or a non-directory ("File" is misleading). And for those functions where you must have a directory, you simply pattern match on it. Yes, I can see that it's quite different. But you would be able to write a proper `getContents` function, for example. And it also represents the hierarchy of what is really going on in the filesystem: "File" being an abstract type that can be a directory, a regular file, a pipe, a socket, ...

**Comment by mrkkrp** [comment]
To pattern-match on constructors you need to export them. Once you export them anyone can create path to file with `/foo/bar/` inside, i.e. you have no useful invariants anymore.

What's wrong with `getContents :: IO ([Path Abs Dir], [Path Abs File])'?

**Comment by hasufell** [comment]
> To pattern-match on constructors you need to export them.

You can fix that with ViewPatterns/PatternSynonyms.

**Comment by chrisdone** [comment]
I'm not going to change this point of the library. It's pretty fundamental
to its advantages.

**Comment by hasufell** [comment]
Uhm, this was more meant as a discussion, not a proposal.

Another thing I cannot figure out how to do properly with this library is when I read symlinks.
We have `readSymbolicLink :: FilePath -> IO FilePath`. What will be returned is not known at compile-time. It can point to a directory, to a regular file or another symlink. So when you do not want `realpath`, because you want to keep the symlink-chain information, how you gonna parse this back into the Path type? If you try out all available parsers, you will get pretty nasty type problems.

I see that the pathtype library has something called `data FileOrDir`. Could something similar be considered for 'path' without it breaking the strictness?
