### ISSUE TITLE
"~/" is rejected as relative path

### ISSUE THREAD

**Issue by hasufell** [chrisdone/path#19]
`~/` is not in the POSIX standard. It's totally [a shell thing](https://www.gnu.org/software/bash/manual/html_node/Tilde-Expansion.html). You can create a directory with the name `~` just fine:
```
# cd /tmp
# mkdir '~'
# ls -la | grep '~'
drwxr-xr-x  2 foo users   4096 Mar 29 16:41 ~
# touch '~/foo'
# ls -la '~'
drwxr-xr-x  2 foo users  4096 Mar 29 16:42 .
drwxrwxrwt 21 root root  20480 Mar 29 16:41 ..
-rw-r--r--  1 foo users     0 Mar 29 16:42 foo
# cd '~'
# pwd
/tmp/~
```

A path library probably shouldn't do any shell-like stuff. `~/` is a valid relative path. If the user expects shell-like expansion of paths, then that has to be handled on another level by the application.

Note that System.FilePath has correct behavior here:
```
Prelude System.FilePath> isRelative "~/"
True
```

**Comment by harendra-kumar** [comment]
I agree its a bit odd to be aware of the "~" expansion at this level. Another discrepancy is that if we are disallowing "~/" then why not "~user/".

**Comment by chrisdone** [comment]
I agree. Let's lift that restriction.
