### ISSUE TITLE
provide a module using posix-paths

### ISSUE THREAD

**Issue by hasufell** [chrisdone/path#20]
Haskell Strings are not particularly safe to represent filepaths which are often obtained via or used with low-level functions where the representation is mostly just a `CString`. This can lead to subtle encoding/decoding bugs when converted to String.

This library still uses `String` under the hood via `System.FilePath`.

There is a library [posix-paths](https://github.com/JohnLato/posix-paths) that handles filepaths as `ByteString`s. It could make sense to add a module that uses that one instead of System.FilePath for posix systems at least. People could use that in conjunction with e.g. `System.Posix.Files.ByteString` from [unix]() and `System.Posix.IO.ByteString` from [unix-bytestring](https://hackage.haskell.org/package/unix-bytestring).

**Comment by chrisdone** [comment]
This library intentionally uses `String` because all the standard Haskell functions use that and take care of encodings in a cross-platform manner.
