### ISSUE TITLE
hardcoded path separator

### ISSUE THREAD

**Issue by harendra-kumar** [chrisdone/path#28]
Does [this](https://github.com/chrisdone/path/blob/609b2585f05a3225800c44302a9391144717aee1/src/Path.hs#L368) work for windows?

```
normalizeDir =
  clean . FilePath.addTrailingPathSeparator . FilePath.normalise
  where clean "./" = ""
        clean ('/':'/':xs) = clean ('/':xs)
        clean x = x
```

**Comment by chrisdone** [comment]
I think not. It should do the same as [here](https://github.com/chrisdone/path/blob/609b2585f05a3225800c44302a9391144717aee1/src/Path.hs#L195).
