### ISSUE TITLE
Discuss: Allow Path Rel Dir to represent an empty path

### ISSUE THREAD

**Issue by harendra-kumar** [chrisdone/path#31]
I needed to represent a relative directory path which may or may not be empty. In absence of an empty `Path Rel Dir` something like `Maybe` will be used to represent this situation. I was wondering if we could allow representation of an empty rel dir.

The operations on an empty path will look like:

```haskell
empty <- parseRelDir "" 
a </> empty == a
```

We will perhaps also have to parse "/" as an empty rel dir because fromRelDir will return it and it is equivalent to the redundant slash in paths. This makes "" and "/" represent the same thing as a rel dir which is true anyway (e.g. a//b == a/b):
```
fromRelDir empty == "/"
parseRelDir "/" == return empty
```

It should probably also resolve #18 because now we represent the dirname of "/" as an empty rel dir:
```haskell
root <- parseAbsDir "/"
dirname empty == empty
dirname root == empty
```

```
isParentOf empty empty == False
isParentOf _ empty == True -- empty is a child of any non-empty rel dir
isParentOf empty _ == True -- empty is parent of every non-empty rel dir
```

Everything looks consistent and it seems to resolve the inconsistency of #18. Does it make sense?

**Comment by chrisdone** [comment]
> We will perhaps also have to parse "/" as an empty rel dir because fromRelDir will return it and it is equivalent to the redundant slash in paths.

These aren't equivalent, as `/` is an absolute path. The empty string isn't a valid file path in any system I'm aware of (Windows or UNIX), so `/` does not denote `[empty filepath] [optional slash]`, because empty filepath isn't a valid concept.

This would be a bad result for e.g. doing `openFile`  on an empty path.

It doesn't make too much sense for me. 😭

**Comment by harendra-kumar** [comment]
> These aren't equivalent, as / is an absolute path. The empty string isn't a valid file path in any system I'm aware of (Windows or UNIX), so / does not denote [empty filepath] [optional slash], because empty filepath isn't a valid concept.

I am not sure I got the point here completely. `/` is an absolute path only when it is parsed into the absolute type using `parseAbsDir`. But if parsed as relative path type it is more like representing the redundant `/` in a path.

Relative path is always used relative to some reference point. A relative `empty` or `null` path is a valid concept because it can be applied to a reference point (an absolute path) and always gives us a valid path as long as the absolute path is valid. We are only talking about a `relative directory path` to be `empty` or `null`. `Relative` and `directory` are key phrases here because otherwise it would not make sense.

> This would be a bad result for e.g. doing openFile on an empty path.

You might have got confused because I did not make it clear that we are talking about only directories here and that too relative only. I agree empty filename would not make sense at all. Also `relative` does not apply to files as such because a relative filepath is really a`relative dir path + filename`. Therefore an empty filename is not a valid concept and opening it does not make sense, I agree.

On the other hand `open` on an empty `relative` dir path does make sense. We have to remember that open always works in a context which is current working directory. For directories an empty path is equivalent to using `.` (and that reminds me that `.` will also get parsed into an empty dir path). So when we say `open <empty relative dir path>` it means opening the current working directory.

An empty relative dir path apparently solves a number of issues nicely:
* We do not need a `Maybe` for a case where we ask the user for a relative path and the user wants to say `Nothing` which means use whatever you have. This is the use case which led me to think about it.
* `.` becomes a valid relative directory path which currently is not accepted as a valid path. This is sort of an aberration or limitation because it is otherwise a perfectly valid concept for which we have no representation. I know we do not accept `..` but `.` is a different case.
* It resolves the inconsistency of `dirname "/"` and represents the result with a valid concept i.e. the resulting path can be used consistently without problems.

So an `empty relative dir path` seems to fit in elegantly as a valid concept. I am not trying to be pushy about it but just trying to bounce around the thoughts and understand where the holes are in the reasoning. I might be smoking something after all :-)

**Comment by harendra-kumar** [comment]
BTW, we do not really have to parse `/` as relative path.  I thought of that only because `toFilePath` returns a trailing `/` at the end, so to be consistent it will return an empty rel dir path as `/` instead of a plain empty string `""`.  If we return it we should also parse it.

But now I think the logical return value for this case is `"./"` instead of `/` or a plain empty `""` and everything works beautifully.

Instead of saying an empty path we can also think about it as a representation of current dir or `.` as a rel dir path.
